//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public int id_libro { get; set; }
        public string nombre { get; set; }
        public int precio_venta { get; set; }
        public double precio_compra { get; set; }
        public Nullable<int> num_pag { get; set; }
    }
}
